import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hiqa1.pooraa.net/');
  await page.getByRole('textbox', { name: 'Email ID' }).click();
  await page.getByRole('textbox', { name: 'Email ID' }).fill('ankit.kashyap@mail.busy.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('link', { name: 'perm_identity Partner' }).click();
  await page.getByRole('button', { name: 'Access Account' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Mobile$/ }).first().click();
  await page.getByRole('textbox', { name: 'description' }).click();
  await page.getByRole('textbox', { name: 'description' }).click();
  await page.getByRole('textbox', { name: 'description' }).fill('1246679871');
  await page.getByRole('button', { name: 'New', exact: true }).click();
  await page.getByText('Purchase New').click();
  await page.getByRole('button', { name: 'A 360 Days' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('ankit');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('8882520239');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ankit.kashyap@mail.busy.in');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Mobile T-Code' }).fill('3195');
  await page.getByRole('textbox', { name: 'Email T-Code' }).click();
  await page.getByRole('textbox', { name: 'Email T-Code' }).fill('2360');
  await page.getByRole('button', { name: 'Purchase' }).click();
});